import { Injectable, BadRequestException, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { randomBytes } from 'crypto';
import type { Device } from '@prisma/client';
import { getModulesForPlan, SystemModule } from '@orbix/types';
import { PrismaService } from '../../../database/prisma.service';
import { LicenseService } from '../../../common/services/license.service';
import { AuthService } from '../auth/auth.service';
import { ActivateDeviceDto } from './dto/activate-device.dto';

export interface TenantSummary {
  id: string;
  name: string;
  slug: string;
  restaurantServiceMode: string;
  kitchenEnabled: boolean;
  /**
   * Effective module list (plan modules ∪ tenant.enabledModules). The comandera
   * drives all navigation/flow decisions off this — never off hardcoded tenant
   * checks. See SystemModule for the canonical keys.
   */
  modules: string[];
  /**
   * Individual business-decision toggles the tenant owner sets in Configuración →
   * Panel de Permisos (web `/tenants/current/settings`). Distinct from RBAC: these
   * gate app *behavior*, not who can do it. Add new keys here as the panel grows.
   */
  businessSettings: TenantBusinessSettings;
}

export interface TenantBusinessSettings {
  /** Comandas: pedir referencia de cuenta al abrir una orden de mostrador.
   *  false → se abre directo con referencia "Mostrador", sin modal. */
  requireCounterReference: boolean;
}

export interface BranchSummary { id: string; name: string }

/**
 * Device registry + device-as-principal validation for the comandera.
 *
 * The device is the durable principal: it holds an opaque `deviceToken` (issued
 * on activate, re-returned on validate) used to authenticate the app and, later,
 * for offline operation. Per-operator identity comes from the PIN (StaffModule).
 */
@Injectable()
export class DevicesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly licenseService: LicenseService,
    private readonly authService: AuthService,
  ) {}

  private newDeviceToken(): string {
    return randomBytes(32).toString('hex');
  }

  private async tenantSummary(tenantId: string): Promise<TenantSummary | null> {
    const tenant = await this.prisma.tenant.findUnique({
      where: { id: tenantId },
      select: { id: true, name: true, slug: true, restaurantServiceMode: true, plan: true, enabledModules: true, settings: true },
    });
    if (!tenant) return null;
    const planModules = getModulesForPlan(tenant.plan) as unknown as string[];
    const effective = new Set([...planModules, ...tenant.enabledModules]);
    const settings = (tenant.settings as Record<string, unknown> | null) ?? {};
    return {
      id: tenant.id,
      name: tenant.name,
      slug: tenant.slug,
      restaurantServiceMode: tenant.restaurantServiceMode,
      kitchenEnabled: effective.has(SystemModule.KITCHEN),
      modules: [...effective],
      businessSettings: {
        // Unset → true (preserva el comportamiento actual: siempre pide referencia).
        requireCounterReference: settings.requireCounterReference !== false,
      },
    };
  }

  private async branchSummary(branchId: string | null): Promise<BranchSummary | null> {
    if (!branchId) return null;
    return this.prisma.branch.findUnique({ where: { id: branchId }, select: { id: true, name: true } });
  }

  // ─── Boot: validate this device ──────────────────────────────────────────────
  /**
   * Called on app start with the device's stable id. Returns whether it is a
   * registered, ACTIVE device and (if so) its tenant/branch/token + live license
   * status so the app can decide: PIN screen vs activation screen.
   */
  async validate(deviceId: string, appVersion?: string) {
    const device = await this.prisma.device.findFirst({ where: { deviceId } });

    if (!device || device.status !== 'ACTIVE' || !device.deviceToken) {
      return { registered: false as const };
    }

    await this.prisma.device.update({
      where: { id: device.id },
      data: { lastSeenAt: new Date(), ...(appVersion ? { appVersion } : {}) },
    });

    const [tenant, branch, licenseStatus] = await Promise.all([
      this.tenantSummary(device.tenantId),
      this.branchSummary(device.branchId),
      this.licenseService.validateLicense(device.tenantId),
    ]);

    return {
      registered: true as const,
      tenant,
      branch,
      deviceToken: device.deviceToken,
      licenseStatus,
    };
  }

  // ─── Activation (public — from the app) ──────────────────────────────────────
  /**
   * Activates a device from the app using either an enrollment `activationToken`
   * (scanned QR generated by an admin) or a `licenseKey` (manual entry). Resolves
   * the tenant, validates the license + device seat limit, registers the device
   * and issues its durable deviceToken.
   */
  async activate(dto: ActivateDeviceDto) {
    let tenantId: string;
    let branchId: string | undefined;

    if (dto.activationToken) {
      const ctx = await this.authService.consumeEnrollmentToken(dto.activationToken);
      tenantId = ctx.tenantId;
      branchId = ctx.branchId;
    } else if (dto.licenseKey) {
      const license = await this.prisma.license.findUnique({
        where: { licenseKey: dto.licenseKey.trim() },
        select: { tenantId: true },
      });
      if (!license) throw new NotFoundException({ code: 'LICENSE_NOT_FOUND', message: 'Licencia no encontrada. Verifica la clave.' });
      tenantId = license.tenantId;
    } else {
      throw new BadRequestException('Provide a licenseKey or an activationToken');
    }

    // License must be valid (active / not expired / not suspended).
    await this.licenseService.assertValid(tenantId);
    const activeLicense = await this.licenseService.getActiveLicense(tenantId);

    // Default the branch to the tenant's main active branch when none was carried.
    if (!branchId) {
      const main = await this.prisma.branch.findFirst({
        where: { tenantId, status: 'ACTIVE' },
        orderBy: { isMain: 'desc' },
        select: { id: true },
      });
      branchId = main?.id;
    }

    const existing = await this.prisma.device.findUnique({
      where: { tenantId_deviceId: { tenantId, deviceId: dto.deviceId } },
    });

    // Enforce the device seat limit only when seating a NEW active device.
    const willConsumeSeat = !existing || existing.status !== 'ACTIVE';
    if (willConsumeSeat && activeLicense?.maxDevices != null) {
      const activeCount = await this.prisma.device.count({ where: { tenantId, status: 'ACTIVE' } });
      if (activeCount >= activeLicense.maxDevices) {
        throw new BadRequestException({
          code: 'LICENSE_DEVICE_LIMIT',
          message: `La licencia permite máximo ${activeLicense.maxDevices} dispositivo(s) activo(s).`,
        });
      }
    }

    const now = new Date();
    const data = {
      name: dto.name ?? existing?.name ?? null,
      model: dto.model ?? existing?.model ?? null,
      os: dto.os ?? existing?.os ?? null,
      appVersion: dto.appVersion ?? existing?.appVersion ?? null,
      type: dto.type ?? existing?.type ?? 'OTHER',
      status: 'ACTIVE' as const,
      branchId: branchId ?? existing?.branchId ?? null,
      licenseId: activeLicense?.id ?? existing?.licenseId ?? null,
      lastSeenAt: now,
    };

    const device = existing
      ? await this.prisma.device.update({
          where: { id: existing.id },
          // keep a stable token across re-activations; mint one only if missing
          data: { ...data, deviceToken: existing.deviceToken ?? this.newDeviceToken() },
        })
      : await this.prisma.device.create({
          data: { tenantId, deviceId: dto.deviceId, deviceToken: this.newDeviceToken(), activatedAt: now, ...data },
        });

    const [tenant, branch, licenseStatus] = await Promise.all([
      this.tenantSummary(tenantId),
      this.branchSummary(device.branchId),
      this.licenseService.validateLicense(tenantId),
    ]);

    return { deviceToken: device.deviceToken, tenant, branch, licenseStatus };
  }

  // ─── Device-as-principal resolution (pin-login + future guard) ────────────────
  /**
   * Resolves + fully authorizes a device by its token: device ACTIVE, tenant
   * ACTIVE/TRIAL, branch ACTIVE (if bound), license valid. Throws a friendly,
   * coded error otherwise. This is the single gate every device-authenticated
   * action should pass through.
   */
  async authorizeByToken(deviceToken: string): Promise<{
    device: Device;
    tenantId: string;
    branchId: string | null;
  }> {
    if (!deviceToken) throw new UnauthorizedException({ code: 'DEVICE_INVALID', message: 'Dispositivo no autorizado.' });

    const device = await this.prisma.device.findUnique({ where: { deviceToken } });
    if (!device || device.status !== 'ACTIVE') {
      throw new UnauthorizedException({ code: 'DEVICE_REVOKED', message: 'Este dispositivo ya no está autorizado.' });
    }

    const tenant = await this.prisma.tenant.findUnique({
      where: { id: device.tenantId },
      select: { status: true },
    });
    if (!tenant || !['ACTIVE', 'TRIAL'].includes(tenant.status)) {
      throw new UnauthorizedException({ code: 'TENANT_INACTIVE', message: 'La empresa no se encuentra activa.' });
    }

    if (device.branchId) {
      const branch = await this.prisma.branch.findFirst({
        where: { id: device.branchId, status: 'ACTIVE' },
        select: { id: true },
      });
      if (!branch) {
        throw new UnauthorizedException({ code: 'BRANCH_INACTIVE', message: 'La sucursal no se encuentra activa.' });
      }
    }

    await this.licenseService.assertValid(device.tenantId);

    return { device, tenantId: device.tenantId, branchId: device.branchId };
  }

  // ─── Admin management (web) ───────────────────────────────────────────────────
  async list(tenantId: string) {
    return this.prisma.device.findMany({
      where: { tenantId },
      orderBy: [{ status: 'asc' }, { lastSeenAt: 'desc' }],
    });
  }

  async revoke(tenantId: string, id: string) {
    const device = await this.prisma.device.findFirst({ where: { id, tenantId } });
    if (!device) throw new NotFoundException('Device not found');
    // Drop the credential so it can't be used again.
    return this.prisma.device.update({ where: { id }, data: { status: 'REVOKED', deviceToken: null } });
  }
}
