/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../../../../web/src/store/waiter-store`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(activation)'}/activate` | `/activate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(activation)'}/qr-scan` | `/qr-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/comandas` | `/comandas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cuenta` | `/cuenta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../../../../../web/src/store/waiter-store`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(activation)'}/activate` | `/activate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(activation)'}/qr-scan` | `/qr-scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/comandas` | `/comandas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/cuenta` | `/cuenta`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../../../../../web/src/store/waiter-store${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(activation)'}/activate${`?${string}` | `#${string}` | ''}` | `/activate${`?${string}` | `#${string}` | ''}` | `${'/(activation)'}/qr-scan${`?${string}` | `#${string}` | ''}` | `/qr-scan${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/comandas${`?${string}` | `#${string}` | ''}` | `/comandas${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/cuenta${`?${string}` | `#${string}` | ''}` | `/cuenta${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/mesas${`?${string}` | `#${string}` | ''}` | `/mesas${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/pin-login${`?${string}` | `#${string}` | ''}` | `/pin-login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../../../../web/src/store/waiter-store`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(activation)'}/activate` | `/activate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(activation)'}/qr-scan` | `/qr-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/comandas` | `/comandas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cuenta` | `/cuenta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin-login` | `/pin-login`; params?: Router.UnknownInputParams; };
    }
  }
}
